/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetocalculadoraemjava;

public class App {
   

    public static void main(String[] args) {
        Calculadora calc = new Calculadora();  
        System.out.println(calc.somar(5, 6));
        System.out.println(calc.subtrair(5, 6));
        System.out.println(calc.dividir(5, 6));
        System.out.println(calc.multiplicar(5, 6));
    }
}
